<#
    .SYNOPSIS
    This scripts create a Minitab network license file.

    .DESCRIPTION
    UAA's Minitab licnese is a network license; however, the licnese ini file created
    must have a unique machineID for each workstation it is deployed to. This script
    programatically creates the necessary file.


    .NOTES
    File Name	: UAA_Minitab_CreateNetworkLicense.ps1
    Author		: Chris Axtell - cbaxtell@uaa.alaska.edu
    Requires	: PowerShell
#>

# The path on the local workstation where the Minitab license file needs to be created
$OutputFile="C:\scripts\MultiUserLicense.ini"

# License File values
$LicenseHeader="[Minitab 17.0]"
$LicenseFile="27000@137.229.186.108"
$Heartbeat=""
$Retries=""
$machineID=$($env:computername)
$EMail="itsdesktop@uaa.alaska.edu"
$firstName="ITS"
$lastName="Desktop"
$guidID="ac12becf-a3bc-424f-974a-c565a4266cf5"
$postedVersion="17.3.1.0"
$isRegistered="TRUE"

# Generic windows setting for adding carriage return, new line codes
$OFS="`r`n"

# Build up the license file syntax
# Yes for some reason the license file generated by Minitab has a blank line at the begin so we include it in ours.
$LicenseFile=$OFS + $LicenseHeader + $OFS + "License File=" + $LicenseFile + $OFS + "Heartbeat=" + $Heartbeat + $OFS + "Retries=" + $Retries + $OFS + "machineID=" + $machineID + $OFS + "EMail=" + $EMail + $OFS + "firstName=" + $firstName + $OFS + "lastName=" + $lastName + $OFS + "guidID=" + $guidID + $OFS + "postedVersion=" + $postedVersion + $OFS + "isRegistered=" + $isRegistered

# Uncomment out the following line for debugging purposes, it'll output the license file to the PowerShell console
#Write-Host $LicenseFile

Set-Content -Encoding Unicode -Path $OutputFile -Value $LicenseFile